/**
 * useDataQuery.js
 * (Renamed to useApiDataQuery for clarity)
 */
import { useQuery } from '@tanstack/react-query';
import { parseQueryString } from './apiConfig';

// --- Generic React Query Hook for API Fetching ---
/**
 * Generic hook to fetch data using a query path generated by the AI.
 * @param {string} rawResponseFromAI The path/query generated by the AI.
 * @param {object} apiConfig The specific configuration (instance, validator) for the target API.
 */
export const useDataQuery = (rawResponseFromAI, apiConfig) => {
    const hasRawResponse = !!rawResponseFromAI; console.log("333333333333333333 useDataQuery")
    const queryPath = hasRawResponse ? apiConfig.validator(rawResponseFromAI) : '';
    const isEnabled = hasRawResponse && apiConfig.enableCondition(queryPath);
    // Determine the base path and parameters
    let requestPath = queryPath;
    let requestParams = {};

    // 💡 Logic to separate path from query string for USGS
    if (apiConfig.queryKey === 'usgs-turbines' && queryPath.includes('?')) {
        [requestPath, requestParams] = queryPath.split('?');
        // Now parse the query string part into an object
        requestParams = parseQueryString(requestParams);
        
        // requestPath will now be 'turbines' (or empty if the validator was simplified)
        // Set requestPath to empty string '' so Axios uses only baseURL and params
        requestPath = ''; 
    }
    // Note: For Niogems, requestPath will be the full path (/page/1/pagesize/10?...) 
    // and requestParams will remain {}, but that's fine.
    
    return useQuery({
      // Use the API key and the queryPath to create a unique query key
      queryKey: [apiConfig.queryKey, queryPath], 
      queryFn: async () => {
        try {
            // Use the passed-in instance (Niogems or USGS)
            const response = await apiConfig.instance.get(requestPath, {
                    params: requestParams 
                });
            return response.data;
        } catch (error) {
            console.error(`${apiConfig.queryKey} API Fetch Error:`, error.response?.data || error.message);
            throw new Error(`API fetch failed: ${error.message}`);
        }
      },
      // Use the dynamically determined enabled state
      enabled: isEnabled, 
      staleTime: 5000, 
    });
};